name: Deploy

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
      - '.github'

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN_ACTION }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        output-file: 'CHANGELOG.md'
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm i
    - run: npm run build
    - run: npm run generate
